print("Day 1-python print function")
print("The Function is declared like this:")
print("print('what to print')")
# second challenge(debugging)
print("Day 1- String Manipulation")
print("String Concatenation is done with the '+' sign.")
print('e.g. print("Hello" + "World")')
print("New lines can be created with a backslash ans n.")
# challenge on input
# name = input("Enter name: ")
# length=len(name)
# print(length)
print(len(input("Enter name: ")))
# last challenge(variable)
a= input("a: ")
b= input("b: ")
print("a= "+a )
print("b= "+b)